<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-29 07:39
=======
# Generated by Django 4.1.2 on 2022-11-01 09:22
>>>>>>> 3b079021a18d588235bcb69df18f66501a7ac45e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default='2022-10-29'),
=======
            field=models.DateField(default='2022-11-01'),
>>>>>>> 3b079021a18d588235bcb69df18f66501a7ac45e
        ),
    ]
