# Generated by Django 4.1.2 on 2022-10-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BarangWishlist',
        ),
    ]
