# Generated by Django 4.1.2 on 2022-10-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_suppliesmodel_delete_barangwishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliesmodel',
            old_name='description',
            new_name='price',
        ),
    ]
