# Generated by Django 4.1.2 on 2022-10-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_rename_description_suppliesmodel_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuppliesModel',
        ),
    ]
