# Generated by Django 4.1.2 on 2022-10-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0004_delete_suppliesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
