# Generated by Django 4.1.2 on 2022-10-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuppliesModel',
        ),
    ]
