# Generated by Django 4.1.2 on 2022-10-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
