# Generated by Django 4.1.2 on 2022-11-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_remove_product_price_product_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
