# Generated by Django 4.1.2 on 2022-11-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
