# Generated by Django 4.1.2 on 2022-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0014_alter_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.FloatField(blank=True, max_length=280, null=True),
        ),
    ]
