# Generated by Django 4.1.2 on 2022-12-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0018_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_finished',
        ),
    ]
