# Generated by Django 4.1.2 on 2022-12-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('first_description', models.TextField()),
                ('secont_description', models.TextField()),
                ('funfact', models.JSONField()),
            ],
        ),
    ]
