# Generated by Django 4.1.2 on 2022-11-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_userprofile_role_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='static/images/default.jpg', null=True, upload_to='userprofile/images'),
        ),
    ]
