# Generated by Django 4.1.2 on 2022-11-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_userprofile_dogtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dogtype',
            field=models.CharField(choices=[('Husky', 'Husky'), ('Bulldog', 'Bulldog'), ('German Shepherd', 'German Shepherd'), ('Poodles', 'Poodles'), ('Shih Tzu', 'Shih Tzu'), ('Pomeranians', 'Pomeranians'), ('Chihuahua', 'Chihuahua'), ('Chow Chow', 'Chow Chow')], default=('Husky', 'Husky'), max_length=15),
        ),
    ]
